baseURL = "http://localhost:1313/"
theme = "ananke"

[params]
  background_color_class = "bg-washed-blue"
  text_color_class = "dark-gray"
  primary_color = "dark-blue"
  font = "system-sans-serif"

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Assignments"
  url = "/assignments/"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

 [[menu.main]]
 name = "Tags"
 url = "/tags/"
 weight = 4

 [[menu.main]]
 name = "Categories"
 url = "/categories/"
 weight = 5
